# Generated by Django 2.2.28 on 2023-08-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cvdh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cvdh',
        ),
        migrations.DeleteModel(
            name='Sffgg',
        ),
    ]
